### ISSUE TITLE
can you indicate your averrage rate ?

### ISSUE THREAD

**Issue by MateoViota** [davidpetrov/Soccer#1]
can you indicate in the project .txt presentation file the averrage rate for each betting type like asian bet or 1x2 best

thanks

**Comment by davidpetrov** [comment]
What do you mean exactly by rate?

**Comment by MateoViota** [comment]
your % of well predicted games on a given period ex:[2012; 2016]

**Comment by davidpetrov** [comment]
It depends on the odds, for main line i.e even odds (1,9 - 2,1) for the over/under market it's about 53%-54%
But you can have higher hit rate and worse results, so it is not a good metric.
Yield or statistic significance of odds history are better for evaluating this kind of model.
